{% set name = "pytravisci" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyTravisCI-{{ version }}.tar.gz
  sha256: 504a65642c805b02e9343c103a40fe016fc5f969f12e82ebc41bee020ef380e9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cryptography
    - python >={{ python_min }}
    - requests
    - setuptools

test:
  imports:
    - PyTravisCI
    - PyTravisCI.communicator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/funilrys/PyTravisCI
  doc_url: https://pytravisci.readthedocs.io/en/latest/
  summary: Just another Python API for Travis CI (API).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
